//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_ImAxisSet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean grab
        {
            get
            {
                return SteamVR_Actions.imAxisSet_grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean detailsOnDemand
        {
            get
            {
                return SteamVR_Actions.imAxisSet_detailsOnDemand;
            }
        }
        
        public virtual SteamVR_Action_Boolean undo
        {
            get
            {
                return SteamVR_Actions.imAxisSet_undo;
            }
        }
        
        public virtual SteamVR_Action_Boolean redo
        {
            get
            {
                return SteamVR_Actions.imAxisSet_redo;
            }
        }
        
        public virtual SteamVR_Action_Boolean brush
        {
            get
            {
                return SteamVR_Actions.imAxisSet_brush;
            }
        }
        
        public virtual SteamVR_Action_Vibration haptics
        {
            get
            {
                return SteamVR_Actions.imAxisSet_haptics;
            }
        }
    }
}
